#!/usr/bin/env bash
echo -e "\e[32m ================= \e[39m"
echo -e "\e[32m     Docker        \e[39m"
echo -e "\e[32m ================= \e[39m"
echo "Install using the convenience script"
echo "from https://docs.docker.com/engine/install/ubuntu/#install-using-the-convenience-script"
sudo curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
sudo rm get-docker.sh

echo -e "\e[32m ================= \e[39m"
echo -e "\e[32m  Docker Compose   \e[39m"
echo -e "\e[32m ================= \e[39m"
echo "Install as a container"
dcTag=$( latest-gh-rel-tag docker compose )
sudo curl -L --fail https://github.com/docker/compose/releases/download/$dcTag/run.sh -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo curl -L https://raw.githubusercontent.com/docker/compose/$dcTag/contrib/completion/bash/docker-compose -o /etc/bash_completion.d/docker-compose
