#!/usr/bin/env bash
user=$1
repo=$2
curl -s https://github.com/$user/$repo/releases |
  grep -Eoi '<a [^>]+>' |
  grep -Eo /$user/$repo/releases/tag/[^\"]+ |
  grep -Eo v?[0-9]+\.[0-9]+\.[0-9]+$ |
  head -1