#!/usr/bin/env bash
echo -e "\e[32m ============ \e[39m"
echo -e "\e[32m  Update NVM  \e[39m"
echo -e "\e[32m ============ \e[39m"
(
  cd "$NVM_DIR"
  git fetch origin
  git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" origin`
) && . "$NVM_DIR/nvm.sh"
nvm --version